config/routes.rb
Rails.application.routes.draw do
  resources :entries

  resources :topics do
	resources :entries
  end

  resources :notebooks do
	resources :topics
  resources :entries
  end

  resources :users do
	resources :notebooks
  end

  root 'users#new'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	has_one :topic
	belongs_to :notebook
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
	belongs_to :user
	has_many :topics, dependent: :destroy
	has_many :entries
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :notebook
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
	has_many :notebooks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:topic_id, :name, :content, :created, :notebook_id,:tipo)
    end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notebook_params
      params.require(:notebook).permit(:user_id, :name, :subject, :created, :cover)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:notebook_id, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render :json => @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :lname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% @topics= @notebook.topics%>
    <%= f.hidden_field( :notebook_id,{id:'notebook_id', value:@notebook.id})%>
    <%= f.hidden_field( :topic_id,{id:'topic_id', name:'entry[topic_id]'})%>
  <div class="field">
    <%= text_field_tag( :topic_display,nil,class: 'form-control',placeholder:'Topic')%>
  </div>
  <div class="field">
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.select(:tipo, options_for_select([['Type','Text'],['Text','Text'],['Drawing','Drawing'],['Image','Image']]), class: 'form-control') %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: 'Enter your text here', class: 'form-control', style:'resize:none;height:200px' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default',id:'but-sbmt-frm' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Name</th>
      <th>Content</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.topic_id %></td>
        <td><%= entry.name %></td>
        <td><%= entry.content %></td>
        <td><%= entry.created %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @entry.topic_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<p>
  <strong>Created:</strong>
  <%= @entry.created %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotebookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap.min.css', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min.js' %>
  <%= javascript_include_tag 'jquery-ui.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notebooks/_form.html.erb
<%= form_for(@notebook) do |f| %>
  <% if @notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% @notebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_area :subject %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.date_select :created %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.text_area :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<h1>Editing notebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<h1>Listing notebooks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Subject</th>
      <th>Created</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notebooks.each do |notebook| %>
      <tr>
        <td><%= notebook.user_id %></td>
        <td><%= notebook.name %></td>
        <td><%= notebook.subject %></td>
        <td><%= notebook.created %></td>
        <td><%= notebook.cover %></td>
        <td><%= link_to 'Show', notebook %></td>
        <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
        <td><%= link_to 'Destroy', notebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New notebook</h1>

<%= render 'form' %>

<%= link_to 'Back', notebooks_path %>

app/views/notebooks/show.html.erb
<div class="navbar navbar-default navbar-static-top" style='margin-top:0'>
	<div class='container-fluid'>
		<div class='navbar-header'>
			<a class='navbar-brand' href='#'>
				Notebook
			</a>
		</div>
		<div class='collapse navbar-collapse navbar-right'>
			<ul class='nav navbar-nav'>
				<li>
					<a href='#'><%= User.find(@notebook.user_id).name %></a>
				</li>
				<li>
					<a href='#'>Settings</a>
				</li>
				<li>
					<a href='#'>Log Out</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class='container' style='width:100%'>
	<div class='col-md-2 hidden-sm hidden-xs'>
		<div class='col-md-12'>
			<h3>You're now seeing:</h3>
			<div class='thumbnail'>
				<%= image_tag "notebook_cover_1.jpg" %>
			</div>
			<p><strong>Name:</strong><%= @notebook.name %></p>
			<p><strong>Subject:</strong><%= @notebook.subject %></p>
			<p><strong>Created:</strong><%= @notebook.created %></p>
		</div>
		<div class='col-md-12'>
			<h3>All your notebooks:</h3>
		</div>
		<% User.find(@notebook.user_id).notebooks.each do |noteb|%>
			<div class='col-md-12'>
				<div class='thumbnail'>
					<%= link_to image_tag("notebook_cover_1.jpg"), notebook_path(noteb) %>
				</div>
				<p><strong>Name:</strong><%= noteb.name %></p>
				<p><strong>Subject:</strong><%= noteb.subject %></p>
				<p><strong>Created:</strong><%= noteb.created %></p>
			</div>
		<% end %>
	</div>
    <% numents= 0
       numpag=0
       @notebook.entries.each do |entry|
         numents+=1;
       end
    %>
	<div class='col-md-10'>
		<h1 class='text-center'><%= @notebook.name %></h1>
		<div class='col-md-6'>
			<div class='thumbnail' id='pg_1_container' style='cursor:pointer;border:none'>
				<img class='img_pag_1'>
				<div class='col-md-10' id='pg_1_content' style='position:absolute;top:69px;left:0;overflow-y:auto'>
					<div class='col-md-12'>
							<% qty= @notebook.entries.count%>
							<%@notebook.entries.each do |entry|%>
								<h3 style='margin-top:3px'><%= entry.name%></h3>
								<p class='text-justify'><%= entry.content%></p>
								<p><%= "created #{entry.created} under #{Topic.find(entry.topic_id).name}"%></p>
								<%@entry= Entry.new%>
							<%end%>
					</div>
				</div>
			</div>
		</div>
		<div class='col-md-6'>
			<div class='thumbnail' style='cursor:pointer;border:none'>
				<%= image_tag('notebook_cover_1.jpg',class: 'img_pag_2')%>
				<div class='col-md-10' style='position:absolute;top:69px;right:0;overflow-y:auto;height:555px;direction:rtl;overflow-x:hidden'>
					<div class='col-md-12' style="direction:ltr">
						<%= @entry= Entry.new
						render 'entries/form'%>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= @topic=Topic.new
    render 'topics/form'%>
<ul id="n_topics" style="display:none">
  <% @notebook.topics.each do|topic|%>
      <li><%=topic.name%></li>
  <%end%>
</ul>
<ul id="n_topics_ids" style="display:none">
  <% @notebook.topics.each do|topic|%>
      <li><%=topic.id%></li>
  <%end%>
</ul>
<p id="last-topic-id"style="display:none"><%= Topic.maximum(:id)%></p>
<%= javascript_include_tag "notebscripts.js"%>
<p id="notice"><%= notice %></p>

app/views/topics/_form.html.erb
<%= form_for @topic, :html => {:style => 'display:none'} do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, 'error') %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notebook_id %><br>
    <%= f.number_field :notebook_id, value: @notebook.id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Notebook</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.notebook_id %></td>
        <td><%= topic.name %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notebook:</strong>
  <%= @topic.notebook_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-center">
    <%= f.text_field :name, :placeholder => "Name",style: "color:black",class: "form-control" %>
  </div>
  <div class="field text-center">
    <%= f.text_field :lname, :placeholder => "Last Name",style: "color:black",class: "form-control" %>
  </div>
  <div class="field text-center">
    <%= f.email_field :email, :placeholder => "Email",style: "color:black",class: "form-control" %>
  </div>
  <div class="field text-center">
    <%= f.password_field :password, :placeholder => "password",style: "color:black",class: "form-control" %>
  </div>
  <div class="actions text-center">
    <%= f.submit :value=> "Get Started!", style: "color:black",class: "btn btn-default"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Lname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.lname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="navbar navbar-default navbar-static-top" style='margin-bottom:0'>
	<div class='container-fluid'>
		<div class='navbar-header'>
			<a class='navbar-brand' href='#'>
				Notebook
			</a>
		</div>
		<form class="navbar-form navbar-right">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Email">
			</div>
			<div class="form-group">
				<input type="password" class="form-control" placeholder="Password">
			</div>
			<button type="submit" class="btn btn-default">Log In</button>
		</form>
	</div>
</div>
<div class='jumbotron' style="margin-top:0;padding-top:0;padding-bottom:0;margin-bottom:0">
  <div class="thumbnail" style="border:none;background:none;padding:0;margin-bottom:0">
        <%= image_tag "guy_notebook.jpg" %>
  </div>
  <div class='container' style='border-radius:10px;padding-top:30px;position:absolute;top:0;left:10%'>
      <div class="col-md-8" style="margin-top:80px;background:rgba(238,238,238,0.5);border-radius:10px">
        <h1>De vuelta al cuaderno</h1>
        <h2>
          ¿Recuerdas cuando tomabas notas para tus materias y para todo en cuadernos?
        </h2>
        <p>Nosotros también. Y sin duda lo extrañamos. Notebook te permite tener tantos cuadernos digitales como quieras Y los organiza para ti automáticamente. Tomar apuntes en un cuaderno nunca fue tan divertido y ordenado</p>
        <h2 >¡Comienza ya!</h2>
        <%= render 'form' %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="navbar navbar-default navbar-static-top" style='margin-top:0'>
	<div class='container-fluid'>
		<div class='navbar-header'>
			<a class='navbar-brand' href='#'>
				Notebook
			</a>
		</div>
		<div class='collapse navbar-collapse navbar-right'>
			<ul class='nav navbar-nav'>
				<li>
					<a href='#'><%= @user.name %></a>
				</li>
				<li>
					<a href='#'>Settings</a>
				</li>
				<li>
					<a href='#'>Log Out</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class='container' style='width:100%'>
	<div class='col-md-3'>
		<h2>Your Account</h2>
		<p><strong>Email:</strong><%= @user.email %></p>
		<p><strong>Name:</strong><%= @user.name %></p>
		<p><strong>Last Name:</strong><%= @user.lname %></p>
		<%= link_to 'Edit', edit_user_path(@user) %> |
		<%= link_to 'Back', users_path %>
	</div>
	<div class='col-md-7'>
		<h2>Your Notebooks</h2>
		<% @user.notebooks.each do |noteb| %>
			<div class='col-md-6' style='margin-bottom:10px'>
				<div class='thumbnail'>
					<%= link_to image_tag("notebook_cover_1.jpg"), notebook_path(noteb) %>
				</div>
				<p><strong>Name: </strong><%= noteb.name %></p>
				<p><strong>Subject: </strong><%= noteb.subject %></p>
				<p><strong>Created on: </strong><%= noteb.created %></p>
			</div>
		<% end %>
	</div>
</div>
<p id="notice"><%= notice %></p>